// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/feed.proto

package feed

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for FeedService service

func NewFeedServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for FeedService service

type FeedService interface {
	Feed(ctx context.Context, in *FeedRequest, opts ...client.CallOption) (*FeedResponse, error)
}

type feedService struct {
	c    client.Client
	name string
}

func NewFeedService(name string, c client.Client) FeedService {
	return &feedService{
		c:    c,
		name: name,
	}
}

func (c *feedService) Feed(ctx context.Context, in *FeedRequest, opts ...client.CallOption) (*FeedResponse, error) {
	req := c.c.NewRequest(c.name, "FeedService.Feed", in)
	out := new(FeedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedService service

type FeedServiceHandler interface {
	Feed(context.Context, *FeedRequest, *FeedResponse) error
}

func RegisterFeedServiceHandler(s server.Server, hdlr FeedServiceHandler, opts ...server.HandlerOption) error {
	type feedService interface {
		Feed(ctx context.Context, in *FeedRequest, out *FeedResponse) error
	}
	type FeedService struct {
		feedService
	}
	h := &feedServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&FeedService{h}, opts...))
}

type feedServiceHandler struct {
	FeedServiceHandler
}

func (h *feedServiceHandler) Feed(ctx context.Context, in *FeedRequest, out *FeedResponse) error {
	return h.FeedServiceHandler.Feed(ctx, in, out)
}
