// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: messageservice.proto

package pb

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MessageService service

func NewMessageServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MessageService service

type MessageService interface {
	ActMessage(ctx context.Context, in *DouyinMessageActionRequest, opts ...client.CallOption) (*DouyinMessageActionResponse, error)
	GetChat(ctx context.Context, in *DouyinMessageChatRequest, opts ...client.CallOption) (*DouyinMessageChatResponse, error)
}

type messageService struct {
	c    client.Client
	name string
}

func NewMessageService(name string, c client.Client) MessageService {
	return &messageService{
		c:    c,
		name: name,
	}
}

func (c *messageService) ActMessage(ctx context.Context, in *DouyinMessageActionRequest, opts ...client.CallOption) (*DouyinMessageActionResponse, error) {
	req := c.c.NewRequest(c.name, "MessageService.ActMessage", in)
	out := new(DouyinMessageActionResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageService) GetChat(ctx context.Context, in *DouyinMessageChatRequest, opts ...client.CallOption) (*DouyinMessageChatResponse, error) {
	req := c.c.NewRequest(c.name, "MessageService.GetChat", in)
	out := new(DouyinMessageChatResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MessageService service

type MessageServiceHandler interface {
	ActMessage(context.Context, *DouyinMessageActionRequest, *DouyinMessageActionResponse) error
	GetChat(context.Context, *DouyinMessageChatRequest, *DouyinMessageChatResponse) error
}

func RegisterMessageServiceHandler(s server.Server, hdlr MessageServiceHandler, opts ...server.HandlerOption) error {
	type messageService interface {
		ActMessage(ctx context.Context, in *DouyinMessageActionRequest, out *DouyinMessageActionResponse) error
		GetChat(ctx context.Context, in *DouyinMessageChatRequest, out *DouyinMessageChatResponse) error
	}
	type MessageService struct {
		messageService
	}
	h := &messageServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MessageService{h}, opts...))
}

type messageServiceHandler struct {
	MessageServiceHandler
}

func (h *messageServiceHandler) ActMessage(ctx context.Context, in *DouyinMessageActionRequest, out *DouyinMessageActionResponse) error {
	return h.MessageServiceHandler.ActMessage(ctx, in, out)
}

func (h *messageServiceHandler) GetChat(ctx context.Context, in *DouyinMessageChatRequest, out *DouyinMessageChatResponse) error {
	return h.MessageServiceHandler.GetChat(ctx, in, out)
}
